# Generated by Django 4.1.7 on 2024-05-11 06:30

from django.db import migrations, models
import django.db.models.deletion
import django_test.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django_test.models.get_datetime_now)),
                ('full_name', models.TextField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=django_test.models.get_datetime_now)),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='django_test.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
